// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // Autogenerated sidebar from docs/ directory structure.
  // _category_.json in each subdirectory controls labels and ordering.
  // sidebar_position frontmatter in each .md file controls item ordering.
  bookSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
